### PR TITLE
Add support for laravel 7

### PR DESCRIPTION
**Pull request by victorlap**

### CODE REVIEW

**Comment by victorlap** [comment]
Maybe add something like the [following](https://github.com/spatie/laravel-medialibrary/blob/master/.github/workflows/run-tests.yml#L13-L25)? Or do you want to drop support for laravel 6 altogether?

**Comment by DarkGhostHunter** [comment]
Well, the plan is to have support for the LTS and the latest version. If GitHub actions can help with testing both framework versions, then that's good. 

Currently I haven't check further GitHub Actions for that matter.

**Comment by DarkGhostHunter** [comment]
After trying with multiple ways to have PHP, Laravel, Orchestra Testbench, PHPUnit and Coveralls playing nicely, I came to the conclusion it's just better to drop support for the last version, otherwise I will have to welcome my old friend **dependency hell**.

**Comment by victorlap** [comment]
If you are still interested. I got it working just now. See https://github.com/victorlap/Laraguard/actions/runs/49411880/workflow

**Pull request merged**
